# Generated by Django 3.1.6 on 2021-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_no',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
