# Generated by Django 3.1.6 on 2021-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210708_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
