# Generated by Django 3.1.6 on 2021-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210723_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approve_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
