# Generated by Django 3.1.6 on 2021-07-29 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payment'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='payment',
        #     name='order_id',
        #     field=models.ForeignKey(default=datetime.date, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.order'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='payment',
        #     name='payment_id',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
    ]
