# Generated by Django 3.1.6 on 2021-07-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210730_0001'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='payment',
        #     name='payment_id',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
    ]
