# Generated by Django 3.1.6 on 2021-07-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_payment_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250, unique=True)),
                ('customer_email', models.CharField(blank=True, max_length=250, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=250, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency_code', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_time', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.order')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
    ]
