# Generated by Django 3.1.6 on 2021-08-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210802_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='customer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='phone_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
