# Generated by Django 3.1.6 on 2021-08-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210802_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
