# Generated by Django 3.1.6 on 2021-08-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210803_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='if_read',
            field=models.BooleanField(default=False),
        ),
    ]
