# Generated by Django 3.1.6 on 2021-08-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_notification_if_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='if_read',
            new_name='is_read',
        ),
    ]
