# Generated by Django 3.1.6 on 2021-08-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_notification_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
